# Generated by Django 5.1.6 on 2025-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
