# Generated by Django 5.1.6 on 2025-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipeingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
