# Generated by Django 5.1.6 on 2025-02-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_rename_ingredients_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
