# Generated by Django 5.1.6 on 2025-02-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_recipeingredient_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='ledger.ingredient'),
        ),
    ]
